### ISSUE TITLE
Initial version feedback

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/component-pusher#2]
The tool is working in general. However, there are several limitations which can make this tool difficult to use.

* Team name must be one word. If you use `example_team` repository creation would not work.
* SSH-Key alias must be one word. If you have it something like `tenant-key` the push of components would not work.
* If you are pushing to `flint` there is a high chance that repository name you use is used and the creation of new repositories would not be possible. Only if you choose a unique name, the push would work. This is not necessarily the problem of this tool, but a problem which one can encounter if the repo name is already used in the tenant.

**Comment by A3a3e1** [comment]
@khanzadyan are you sure?
I use 'ps_team_sprint_review' as a team name and 'flint-garry' as an ssh alias and everything is fine

**Comment by khanzadyan** [comment]
Strange, now I'm not sure about anything. It kept giving me `403`s until I simplified and made the changes I describe.
